config/routes.rb
Myapp::Application.routes.draw do

  constraints(:host => /^hashfollow.com/) do
    root :to => redirect("http://www.hashfollow.com")
    match '/*path', :to => redirect {|params| "http://www.hashfollow.com/#{params[:path]}"}
  end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "user/edit"
  put "user/update"

  resources :terms do
    member do
      post :disable
      post :enable
      post :run
      get :log
    end
  end

  root :to => "home#index"

  get "home/index"
  get "home/search"
  get "/why", :to => "home#why"
  get "/who", :to => "home#who"
  get "/plans", :to => "home#plans", :as => :plans
  get "/contact", :to => "contact_us/contacts#new"

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  get '/test', to: "home#test"

end

app/models/term.rb
class Term < ActiveRecord::Base

  DAILY = 1
  TWICE_DAILY = 2
  HOURLY = 3
  WEEKLY = 4

  def self.interval_map
    {
      "Daily" => DAILY#,
      #"Twice Daily" => TWICE_DAILY,
      #"Hourly" => HOURLY,
      #"Weekly"=> WEEKLY
    }
  end

  scope :disabled, where(is_disabled: true)
  scope :enabled, where(is_disabled: false)

  validates_presence_of :name, :max_to_follow
  validates :max_to_follow, :inclusion => { :in => [30, 20, 10, 5],
    :message => "%{value} is not valid" }
  validates :name, :uniqueness => { :scope => :user_id, :message => "has already been added" }

  has_many :followings
  belongs_to :user
  attr_accessible :interval, :max_to_follow, :name, :notify, :run_now

  attr_accessor :run_now

  def run_now
    self[:run_now] || true
  end

  after_save :run_now_check

  def run_now_check
    if run_now
      self.run_task!
    end
    true
  end

  MAX_ATTEMPTS = 3

  def run_task!
    Resque.enqueue(TermFollower, self.id)
  end

  def disable!
    self.update_attribute(:is_disabled, true)
  end

  def enable!
    self.update_attribute(:is_disabled, false)
  end

  def self.follow_scheduled_terms
    Term.enabled.all.each do |term|
      Resque.enqueue(TermFollower, term.id)
    end
  end

  def followings_a_week_ago
    self.followings.where("created_at < :week", {:week => 1.week.ago}).active
  end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController

  before_filter :login_required
  before_filter :terms_count_limit, :only => [:new, :create]

  # GET /terms
  # GET /terms.json
  def index
    @terms = current_user.terms

    respond_to do |format|
      format.html {
        if @terms.count <= 0 
          redirect_to new_term_path
        end
      }
      format.json { render json: @terms }
    end
  end

  # GET /terms/1
  # GET /terms/1.json
  def show
    @term = current_user.terms.find(params[:id])
    @followings = @term.followings.page(params[:page] || 0).per(10)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @term }
    end
  end

  # GET /terms/new
  # GET /terms/new.json
  def new
    @term = current_user.terms.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @term }
    end
  end

  # GET /terms/1/edit
  def edit
    @term = current_user.terms.find(params[:id])
  end

  # POST /terms
  # POST /terms.json
  def create
    @term = current_user.terms.new(params[:term])

    respond_to do |format|
      if @term.save
        format.html { redirect_to @term, notice: 'Term was successfully created.' }
        format.json { render json: @term, status: :created, location: @term }
      else
        format.html { render action: "new" }
        format.json { render json: @term.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /terms/1
  # PUT /terms/1.json
  def update
    @term = current_user.terms.find(params[:id])

    respond_to do |format|
      if @term.update_attributes(params[:term])
        format.html { redirect_to @term, notice: 'Term was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @term.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /terms/1
  # DELETE /terms/1.json
  def destroy
    @term = current_user.terms.find(params[:id])
    @term.destroy

    respond_to do |format|
      format.html { redirect_to terms_url }
      format.json { head :no_content }
    end
  end

  def disable
    @term = Term.find(params[:id])
    @term.disable!

    respond_to do |format|
      format.js
      format.html {
        redirect_to :back, :notice => "Disabled the term."
      }
      format.json { render json: @term }
    end
  end

  def enable
    @term = Term.find(params[:id])
    @term.enable!

    respond_to do |format|
      format.js
      format.html {
        redirect_to :back, :notice => "Enabled the term."
      }
      format.json { render json: @term }
    end
  end

  def run
    @term = Term.find(params[:id])
    @term.run_task!

    respond_to do |format|
      format.js
      format.html {
        redirect_to :back, :notice => "Successfully scheduled the search and follow task."
      }
      format.json { render json: @term }
    end
  end

  def log

  end

  private

  def terms_count_limit
    if current_user.terms.count >= 3
      redirect_to root_url, notice: "Can create only 3 terms with free plan. <a href='/plans'>Sing up for premium membership</a>"
    end
  end
end

app/helpers/terms_helper.rb
module TermsHelper
  def can_add_term?
    current_user.terms.count < 3
  end

  def last_run_time(term)
    term.last_run_at.present? ? time_ago_in_words(term.last_run_at) + " ago" : "never"
  end
end

app/views/terms/_following.html.erb
<div class='following'>
  &nbsp;&nbsp;<span style="font-size:16px;"><a href="http://www.twitter.com/<%= following.screen_name %>" target="_blank"><%= following.screen_name %></a> for </span>
  <!--
  <span class="actions" style="display:inline-block;float:right;padding-top:-5px;display:none;">
    <%= link_to "Unfollow", "#", :class => "btn btn-mini" %>
  </span>
-->
  <div class="tweet" display:table-row;"">
    <a href="http://www.twitter.com/<%= following.screen_name %>" class="thumb" style="display:inline-block;float:left;padding:4px 10px;" target="_blank" >
      <%= image_tag following.tweet.user.profile_image_url, :style => "width:48px;height:48px;" %>
    </a>
    <div class="body">
      <div class="text">
        <%= format_tweet following.tweet.text %>
      </div>
      <%= link_to time_ago_in_words(following.tweet.created_at) + " ago", "https://twitter.com/haleakalari/status/" + following.tweet.id.to_s, :target => "_blank" %>
    </div>
    <div style="clear:both;"></div>
  </div>
</div>

app/views/terms/_form.html.erb
<%= simple_form_for @term, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name, :label => "Term", :hint => "#competitor or @competitor. This term will be used to find users using competitor's products", :input_html => { :placeholder => "#something" } %>
  <%= f.input :interval, :collection => Term.interval_map, :include_blank => false, :hint => "Can run only daily in free version" %>
  <%= f.input :max_to_follow, :label => "Maximum users", :collection => [30,20,10,5], :include_blank => false, :hint => "Maximum users to follow in single run." %>
  <!--  Disabled notification on per term basis -->
  <!--
  <%= f.input :notify, :hint => "Notify me when new users are followed" %>
  -->
  <% unless @term.is_disabled? %>
  <%= f.input :run_now, :as => :boolean %>
  <% end %>

  <div class="form-actions">
    <%= f.submit @term.new_record? ? "Create Term" : "Update Term", :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                terms_path, :class => 'btn' %>
  </div>
<% end %>

<% content_for :right do %>
  <div class="tweeter_results">
    <table>
      <div class="tweeter_result">
      </div>
    </table>
  </div>
<% end %>

app/views/terms/_run_log.html.erb
<% if followings.count > 0 %>
	<h1><%= term.name %></h1>
	<h3>Followed <%= followings.count %> users.</h3>
	<p>
	  <% followings[0..3].each do |following| %>
	  <%= render "terms/following", :following => following %>
	  <% end %>
	  <% if followings.count > 3 %>
	  <%= link_to "and few more", term_url(term, :only_path => false) %>
	  <% end %>
	</p>
<% end %>

app/views/terms/edit.html.erb
<%- model_class = Term -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/terms/index.html.erb
<h3>Tracking terms</h3>

<div class="terms">
  <% @terms.each do |term| %>
  <div class="term <%= term.is_disabled ? "disabled" : "" %>">
    <%= link_to term.name, term, :class => "name" %>
    <div class="actions">
      <%= link_to "Run Now", term.is_disabled ? "javascript:void(0)" : run_term_path(term), :class => "btn btn-mini btn-inverse " + (term.is_disabled ? "disabled" : ""), :method => :post %>
      <% if term.is_disabled? %>
      <%= link_to "Enable", enable_term_path(term), :class => "btn btn-mini btn-success", :method => :post %>
      <% else %>
      <%= link_to "Disable", disable_term_path(term), :class => "btn btn-mini btn-danger", :method => :post %>
      <% end %>
      <%= link_to "Delete", term, :method => :delete, :class => "btn-mini", :confirm => "This is not reversible" %>
    </div>
    <div class="info">
      Followed <%= term.followings_count || "0" %> users till now<br />
      <span class="time">Last run <%= last_run_time(term) %></span>
    </div>
  </div>
  <% end %>
</div>

<br />

<% unless can_add_term? %>
<%= link_to "Track new term", "javascript:void(0)", :class => "btn", :disabled => true %> <i> Can only add 3 terms in free plan. <a href="/plans">See plans</a></i>
<% else %>
<%= link_to "Track new term", new_term_path, :class => "btn btn-primary " + (@terms.present? ? "" : "btn-large") %>
<% end %>

<br />
<br />

app/views/terms/new.html.erb
<%- model_class = Term -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/terms/show.html.erb
<%- model_class = Term -%>
<h1><%= link_to @term.name, @term %></h1>

<div class="form-actions" style="border-top:0;border-bottom:1px;">
  <%= link_to "Run Now", @term.is_disabled ? "javascript:void(0)" : run_term_path(@term), :class => "btn btn-inverse " + (@term.is_disabled ? "disabled" : ""), :method => :post %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_term_path(@term), :class => 'btn' %>
  <% if @term.is_disabled? %>
  <%= link_to "Enable", enable_term_path(@term), :class => "btn btn-success", :method => :post %>
  <% else %>
  <%= link_to "Disable", disable_term_path(@term), :class => "btn btn-danger", :method => :post %>
  <% end %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              term_path(@term),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-link' %>
</div>

<h3 style="display:inline-block;">Recently followed</h3> <i style="float:right;padding-right:10px;margin-top:20px;"> Last run <%= last_run_time(@term) %></i>

<% if @followings.count > 0 %>
<div class="followings">
  <% @followings.each do |following| %>
  <%= render "terms/following", :following => following %>
  <% end %>
  <%= paginate @followings %>
</div>
<% else %>
  <div><i>No one followed so far</i></div>
<% end %>