config/routes.rb
Myapp::Application.routes.draw do

  constraints(:host => /^hashfollow.com/) do
    root :to => redirect("http://www.hashfollow.com")
    match '/*path', :to => redirect {|params| "http://www.hashfollow.com/#{params[:path]}"}
  end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "user/edit"
  put "user/update"

  resources :terms do
    member do
      post :disable
      post :enable
      post :run
      get :log
    end
  end

  root :to => "home#index"

  get "home/index"
  get "home/search"
  get "/why", :to => "home#why"
  get "/who", :to => "home#who"
  get "/plans", :to => "home#plans", :as => :plans
  get "/contact", :to => "contact_us/contacts#new"

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  get '/test', to: "home#test"

end

app/views/contact_us/contacts/new.html.erb
<h2><%= t('.contact_us') %></h2>
<%= form_for @contact, :url => contacts_path, :html => {:class => 'formtastic'} do |f| %>
  <% if ContactUs.require_name %>
    <li class='string required' id='contact_us_contact_name_input'>
      <%= f.label :name, (t('.name') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
      <%= f.text_field :name %>
      <% if f.object.errors[:name].present? %>
        <p class='inline-error'><%= f.object.errors[:name].join(' and ') %></p>
      <% end %>
    </li>
  <% end %>
  <li class='string required' id='contact_us_contact_email_input'>
    <%= f.label :email, (t('.email') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
    <%= f.text_field :email %>
    <% if f.object.errors[:email].present? %>
      <p class='inline-error'><%= f.object.errors[:email].join(' and ') %></p>
    <% end %>
  </li>
  <% if ContactUs.require_subject %>
    <li class='string required' id='contact_us_contact_subject_input'>
      <%= f.label :subject, (t('.subject') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
      <%= f.text_field :subject %>
      <% if f.object.errors[:subject].present? %>
        <p class='inline-error'><%= f.object.errors[:subject].join(' and ') %></p>
      <% end %>
    </li>
  <% end %>
  <li class='text required' id='contact_us_contact_message_input'>
    <%= f.label :message, (t('.message') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
    <%= f.text_area :message %>
    <% if f.object.errors[:message].present? %>
      <p class='inline-error'><%= f.object.errors[:message].join(' and ') %></p>
    <% end %>
  </li>
  <li class='commit'>
    <%= f.submit :submit, :alt => t('.submit'), :class => 'submit create', :label => t('.submit'), :title => t('.submit') %>
  </li>
<% end %>

app/views/contact_us/contacts/new_formtastic.html.erb
<h2><%= t('.contact_us') %></h2>
<%= semantic_form_for @contact, :url => contacts_path do |f| %>
  <%= f.input :name, :label => t('.name') if ContactUs.require_name %>
  <%= f.input :email, :label => t('.email') %>
  <%= f.input :subject, :label => t('.subject') if ContactUs.require_subject %>
  <%= f.input :message, :as => :text, :label => t('.message') %>
  <%= f.action :submit, :label => t('.submit'), :button_html => { :alt => t('.submit'), :id => 'contact_us_contact_submit', :title => t('.submit') } %>
<% end %>

app/views/contact_us/contacts/new_simple_form.html.erb
<h2><%= t('.contact_us') %></h2>
<%= simple_form_for @contact, :url => contacts_path, :html => { :class => "form-horizontal" } do |f| %>
  <%= f.input :name, :label => t('.name') if ContactUs.require_name %>
  <%= f.input :email, :label => t('.email') %>
  <%= f.input :subject, :label => t('.subject') if ContactUs.require_subject %>
  <%= f.input :message, :as => :text, :label => t('.message'), :input_html => { :rows => "8" } %>
  <div class="form-actions">
    <%= f.button :submit, "Send Message", :label => t('.submit'), :button_html => { :alt => t('.submit'), :id => 'contact_us_contact_submit', :title => t('.submit') }, :class => "btn-primary" %>
  </div>
<% end %>