config/routes.rb
Myapp::Application.routes.draw do

  constraints(:host => /^hashfollow.com/) do
    root :to => redirect("http://www.hashfollow.com")
    match '/*path', :to => redirect {|params| "http://www.hashfollow.com/#{params[:path]}"}
  end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "user/edit"
  put "user/update"

  resources :terms do
    member do
      post :disable
      post :enable
      post :run
      get :log
    end
  end

  root :to => "home#index"

  get "home/index"
  get "home/search"
  get "/why", :to => "home#why"
  get "/who", :to => "home#who"
  get "/plans", :to => "home#plans", :as => :plans
  get "/contact", :to => "contact_us/contacts#new"

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  get '/test', to: "home#test"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "HashFollow" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag '/favicon.ico?DEL2', :rel => 'shortcut icon' %>

    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-15652129-17']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>
  </head>
  <body>
    <div id="fb-root"></div>
    <!-- ClickTale Top part -->
    <script type="text/javascript">
    var WRInitTime=(new Date()).getTime();
    </script>
    <!-- ClickTale end of Top part -->

    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_IN/all.js#xfbml=1&appId=128174990644229";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/"><%= image_tag "HashFollow_small.png", :style => "position:Absolute;max-height:50px;padding-botom:-10px;" %></a>
          <div class="container nav-collapse">
            <ul class="nav">
            </ul>
            <ul class="nav pull-right">
              <li style="margin-top:10px;width:100px;">
                <div class="fb-like" data-href="http://www.facebook.com/HashFollow" data-send="false" data-layout="button_count" data-width="100" data-show-faces="false"></div>
              </li>
              <% if current_user %>
              <li>
                <%= link_to "Settings", "/user/edit", :style => "" %>
              </li>
              <li>
                <%= link_to "Sign out" + " @" + current_user.name, signout_path, :style => "fasdloat:right;padasdding:5px;" %>
              </li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <% if flash[:notice] %>
        <p class="alert alert-info" style="margin-top:5px;"><%=raw notice %><a class="close" data-dismiss="alert" href="#">×</a></p>
      <% end %>
      <% if flash[:alert] %>
        <p class="alert alert-error" style="margin-top:5px;"><%=raw alert %><a class="close" data-dismiss="alert" href="#">×</a></p>
      <% end %>
        <div class="row">
          <div class="span9">
             <%= yield %>
          </div>
          <div class="span3">
            <% if !current_user %>
              <blockquote cite="http://www.worldwildlife.org/who/index.html">
                <p>I got 20 new followers in first week after signing up. It takes no time to set it up and you get free users.</p>
                <small>Dan Pinter <cite title="Source Title"></cite></small>
              </blockquote>
              <blockquote cite="http://www.worldwildlife.org/who/index.html">
                <p>My startup was able to lure some users from a competing poduct :)</p>
                <small>Amit Ambardekar<cite title="Source Title"></cite></small>
              </blockquote>
              <iframe src="//www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2FHashFollow&amp;width=270&amp;height=290&amp;colorscheme=light&amp;show_faces=true&amp;border_color&amp;stream=false&amp;header=true&amp;appId=484552251585691" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:270px; height:290px;" allowTransparency="true"></iframe>
            <% else %>
              <%= yield :right if content_for?(:right) %>
              <div class="well sidebar-nav">
                <h3></h3>
                <ul class="nav nav-list">
                  <li class="nav-header"></li>
                  <li><%= link_to "Dashboard", "/"  %></li>
                  <li>
                    <% if can_add_term? %>
                      <%= link_to "New Term", "/terms/new"  %>
                    <% else %>
                      <%= link_to "New Term", "javascript:void(0)", :class => "link-disabled" %>
                    <% end %>
                  </li>
                </ul>
                <ul class="nav nav-list" style="display:none;">
                  <li class="nav-header"></li>
                  <li class="divider"></li>
                  <li><%= link_to "Why", "/why"  %></li>
                  <li><%= link_to "Conact", "/contact"  %></li>
                </ul>
              </div><!--/.well -->
            <% end %>
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <br />
        <p>&copy; HashFollow 2012 | <%= link_to "Why", "/why" %> | <%= link_to "Who", "/who" %> | <%= link_to "Conact", "/contact"  %> <!-- | <%= link_to "Plans", "/plans" %>--></p>
        <br />
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

    <!-- ClickTale Bottom part -->
    <div id="ClickTaleDiv" style="display: none;"></div>
    <script type="text/javascript">
    if(document.location.protocol!='https:')
      document.write(unescape("%3Cscript%20src='http://s.clicktale.net/WRe0.js'%20type='text/javascript'%3E%3C/script%3E"));
    </script>
    <script type="text/javascript">
    if(typeof ClickTale=='function') ClickTale(25998,1,"www02");
    </script>
    <!-- ClickTale end of Bottom part -->


  </body>
</html>